# id: (country, design, N, population, PMDD ascertainment, domains)
C={}
def c(i,country,design,n,pop,asc,dom): C[i]=dict(country=country,design=design,n=n,population=pop,ascertainment=asc,domains=dom.split())
c(208,'NR','Cross-sectional (phase comparison)','150','University students','Clinical interview + screening tool','ANX MER PD')
c(242,'Germany','Ambulatory assessment (EMA)','122','Community women','Prospective daily ratings','MER DEP')
c(286,'Japan','Retrospective chart review','290','Adolescent clinical patients','PMDD assessment scale','COM DEP')
c(288,'China (Hong Kong)','Cross-sectional','541','University students','Screening tool (high-risk PMDD)','DEP ANX IF COP')
c(290,'Switzerland','Cross-sectional (national health survey)','3913','Population-based sample','Screening tool (PSST-based)','PD')
c(296,'United Kingdom','Qualitative (interviews)','17','Clinically diagnosed women','Specialist diagnosis + PSST','EXP PD')
c(311,'Canada','Qualitative (interviews)','10','People living with PMDD','Self-identified/diagnosed','EXP SUI')
c(336,'Saudi Arabia','Cross-sectional','144','Nursing students','Screening tool (PSST)','PD')
c(350,'Iran','Cross-sectional','210','University students','Screening tool (PSST)','PER')
c(387,'Jordan','Prospective-correlational','858','University students','Daily symptom records','FUN')
c(424,'Poland','Cross-sectional + prospective','228 / 90','Community women','Retrospective + prospective diagnosis','TRA PD DEP')
c(443,'Jordan','Cross-sectional','254','University students/staff','DSM-IV-TR research criteria','PD COP FUN')
c(445,'Japan','Chart review','66','Untreated clinical patients','Clinical diagnosis','QOL')
c(452,'Ethiopia','Cross-sectional','529','University students','DSM-based criteria','FUN')
c(455,'Belgium','Cross-sectional + two-phase follow-up','380','Community women','Screening tool (PSST)','DEP ANX PD MER')
c(483,'Canada','Daily diary (32 days)','69','Female cannabis users','Clinical interview + prospective mood','DEP COP COM')
c(485,'Sweden','Cross-sectional + prospective (LifeGene cohort)','17284','Population-based cohort','Modified PSST + registry diagnoses','QOL')
c(510,'United States','Cross-sectional (national survey, CPES)','8694','Nationally representative sample','Diagnostic interview (DSM-IV)','COM')
c(553,'Israel','Cross-sectional','648','University students','Screening tool (PSST)','MER')
c(604,'United States','Prospective daily ratings','267','Community women','Prospective (DRSP)','FUN IF')
c(610,'Netherlands','Cross-sectional','70','Autistic and non-autistic women','Diagnostic assessment','COM')
c(628,'United States','Case-control','36','Community women','Prospective daily ratings (DSM-5)','MER IF PD')
c(693,'Taiwan','Cross-sectional','383','Outpatients with mood disorders','Diagnostic interview (SADS-L)','SUI COM')
c(695,'United States','Cross-sectional (national survey, CPES)','3965','Nationally representative sample','Diagnostic interview (DSM-IV)','SUI')
c(698,'United States','Case-control (laboratory stressor)','52','Community women','Clinical interview + 30-day prospective ratings','MER COP')
c(711,'Turkey','Cross-sectional','92','Gynaecology outpatients','Clinical diagnosis','DEP ANX QOL FUN')
c(728,'Japan','Cross-sectional','618','High school students','Screening questionnaire','FUN')
c(738,'Taiwan','Case-control','142','Community women','Psychiatric interview + 3-cycle follow-up','DEP ANX MER FUN')
c(798,'United States','Case-control','164','Young women with/without depression','Structured interview (SCID-PMDD)','DEP COM')
c(808,'United States','Cross-sectional (online survey, secondary analysis)','949','Online community sample','Screening tool (PMSIS)','QOL IF')
c(848,'Mexico','Cross-sectional','141','Perimenopausal clinic patients','History of PMDD (clinical assessment)','DEP')
c(976,'Iran','Cross-sectional','602','School adolescents','DSM-IV / ICD-10 criteria','QOL IF')
c(1031,'Bangladesh','Cross-sectional','516','University students','Screening tool (PSST)','SUI DEP ANX PD')
c(1036,'NR (online panel)','Cross-sectional (online survey)','715','Young adults (18-34)','Screening tool (PSST)','COM DEP ANX')
c(1037,'Germany','Ambulatory assessment (EMA)','120','Community women','Prospective daily ratings','MER')
c(1038,'China','Cross-sectional','10042','School adolescents','Modified C-PEX questionnaire (screening)','TRA COM')
c(1041,'Sweden','Prospective cohort (registry-linked)','15606','Population-based cohort','Modified PSST','IF')
c(1053,'Taiwan','Case-control','196','Community women','Psychiatric interview + 3-cycle prospective','MER DEP ANX PD')
c(1061,'Taiwan','Case-control','142','Community women','Psychiatric interview + 2-cycle prospective','PER DEP ANX')
c(1074,'Japan','Cross-sectional','212','Pregnant women','PMDD scale','DEP')
c(1079,'Sweden','Longitudinal cohorts (two)','NR','Pregnant/postpartum women','Retrospective self-report','DEP ANX')
c(1083,'United Kingdom','Cross-sectional (online survey)','403 / 151','People with PMDD, partners, controls','Self-reported diagnosis','QOL IF')
c(1095,'China','Cross-sectional','262','Women with bipolar disorder','Screening tool (PSST)','COM DEP')
c(1111,'Japan','Cross-sectional (online survey)','2000','Full-time working women','PMDD scale','TRA')
c(1116,'Online (international)','Qualitative (thematic analysis of forum posts)','NR (top posts)','Online PMDD community (r/PMDD)','Self-identified','COP EXP IF')
c(1117,'Online (international)','Cross-sectional (online survey)','308','PMDD patients (IAPMD followers)','Self-reported diagnosis','EXP SUI IF')
c(1118,'Turkey','Case-control','62','Psychiatric outpatients','Clinical diagnosis','DEP')
c(1137,'Lebanon','Cross-sectional (online survey)','NR','University students','Self-report PMDD measure','TRA DEP PD')
c(1141,'Japan','Cross-sectional (nationwide online survey)','4818','General workforce','Self-report screening','FUN')
c(1155,'Mexico','Cross-sectional','134','Women with rheumatoid arthritis and controls','Screening tool (PSST)','FUN')
c(1158,'Sweden','Cross-sectional (trial baseline)','110','Clinically confirmed PMDD','Prospective daily ratings (DSM-5)','SUI DEP')
c(1159,'Turkey','Cross-sectional (online survey)','408','Healthy women','Screening tool (PSST)','PER SUI COM')
c(1162,'Australia','Retrospective clinical database','100','Specialist clinic patients','Clinical diagnosis','TRA')
c(1173,'Taiwan','Nationwide registry cohort','41110','National insurance database','Clinical diagnosis (registry)','DEP COM')
c(1175,'Spain','Cross-sectional','105','General population and MDD patients','Semi-structured interview (DSM-5)','DEP FUN IF')
c(1186,'Online (international)','Cross-sectional (global online survey)','599','People with prospectively diagnosed PMDD','Self-reported prospective diagnosis','SUI COM')
c(1189,'Turkey','Cross-sectional','70','University students','DSM-5 criteria','FUN')
c(1200,'Online (international)','Cross-sectional (IAPMD global survey)','2512','Patients seeking care for PMDD','Self-reported symptoms/diagnosis','EXP')
c(1205,'Germany','Ambulatory assessment (EMA)','122','Community women','Prospective daily ratings','PD MER')
c(1224,'Spain','Case-control','264','Hospital and family-planning clinic attendees','Clinical diagnosis','PD PER COP')
c(1246,'Poland','Experimental cross-sectional','293','Community women','Screening tool (PSST)','MER DEP')
c(1250,'France','Cross-sectional','232','Hospitalised suicide attempters','Algorithm from shortened PAF','PER SUI MER')
c(1258,'Germany','Ambulatory assessment (EMA)','122','Community women','Prospective daily ratings','MER')
c(1266,'Brazil','Cross-sectional (population-based)','727','Young adult community women','Diagnostic interview (MINI-Plus)','COM SUI DEP ANX')
c(1267,'Iran','Case-control','240','Hospitalised suicide attempters and controls','Psychiatric interview (DSM-5)','SUI')
c(1275,'United States','Cross-sectional','731','College women','Screening tool (provisional diagnosis)','ANX QOL')
c(1277,'Netherlands','Cross-sectional','209','Adult ADHD outpatients','Diagnostic interview (MINI-Plus)','COM')
c(1285,'Iran','Cross-sectional','475','High school students','Screening tool (PSST)','MER DEP')
c(1312,'United States','Secondary analysis (STEP-BD cohort)','1099','Women with bipolar disorder','DSM-5 criteria (self-report questionnaire)','COM DEP')
c(1314,'United States','Cross-sectional + prospective (two studies)','735 / 85','College women','Retrospective screening + 60-day prospective','MER COP ANX')
c(1318,'Iceland','Cross-sectional (SAGA cohort)','11973','Population-based cohort','Modified PSST','TRA')
c(1323,'Taiwan','Case-control','155','Community women','Psychiatric interview','COM PD MER')
c(1338,'United States','Cross-sectional (national surveys)','2718','Asian, Latina and Black women','Diagnostic interview (WMH-CIDI)','TRA')
c(1347,'Kuwait','Prospective observational','110','Nursing students','Prospective (Arabic DRSP)','FUN')
c(1354,'Sweden','Population registry cohort + sibling analysis','1472379','National population','Clinical indication (registry)','SUI')
c(1373,'Multinational','Prospective web-based study','822','Community women','Prospective (DRSP)','QOL IF FUN')
c(1378,'South Korea','Cross-sectional (nationwide survey)','2499','Nationally representative sample','Diagnostic interview (K-CIDI)','COM SUI DEP')
c(1400,'United States','Prospective daily ratings (30 days)','61','Community women','Prospective daily ratings','MER')
c(1421,'Nigeria','Cross-sectional','985','Secondary school adolescents','Self-report questionnaire','PD')
c(1464,'United States','Case-control','124','Clinical research participants','Prospective confirmation','PER')
c(1472,'Sweden','Case-control','85','Clinical patients and controls','Prospective confirmation','PER')
c(1490,'Turkey','Case-control','100','Clinical patients and controls','DSM criteria','MER')
c(1515,'Italy','Cross-sectional','92','Women with bipolar disorder','Structured interview (SCID-I)','COM')
c(1585,'Poland','Cross-sectional (population study)','1540','Community women','Questionnaire-based diagnosis','IF')
c(1800,'Ethiopia','Cross-sectional','548','High school students','DSM-5 criteria','DEP PD')
